### ISSUE TITLE
CSS classes missing for Ghost 2.x

### ISSUE THREAD

**Issue by yoeriboven** [nahuelsanchez/pale-ghost#1]
Pale can be activated but only with errors.

> The `.kg-width-wide` CSS class is required to use your theme with 2.0
> The `.kg-width-full` CSS class is required to use your theme with 2.0
> The `.kg-gallery-container` CSS class is required to use your theme with 2.0
> The `.kg-gallery-row` CSS class is required to use your theme with 2.0
> The `.kg-gallery-image` CSS class is required to use your theme with 2.0

**Comment by nahuelsanchez** [comment]
Hi @yoeriboven,

Thanks for reporting this (and sorry it took me too long to reply).

I was aware of the "issue" when Ghost 2 was released, but I wasn't sure if I should fix that or not because the whole idea behind the Pale Ghost theme is to not have any CSS, that's why the bug was "expected".

Anyway, I added the classes just to avoid confusions and doubts when anybody activates the theme or runs the GScan.

I released Pale Ghost version 1.1.1 with this issue fixed, you can check/download it here  https://github.com/nahuelsanchez/pale-ghost/releases.

Thanks again,

Nahuel
